### ISSUE TITLE
Editor: Remove backwards-compatibility fields

### ISSUE THREAD

**Issue by buerge3** [nasa/CTF#12]
The telemetry_watch_list and command_watch_list fields are automatically added to CTF scripts when using the CTF Editor. These fields are not used by the current version of CTF; rather, they are only included for backwards-compatibility with older versions of CTF. These fields should be removed to prevent code clutter, and to prevent confusion, since only the latest version of CTF will be used for verification. Currently, I am manually deleting these fields every time before checking in the CTF scripts to our code base.

**Comment by blueoceanwater** [comment]
This issue is fixed and will be released in v1.4.
