### ISSUE TITLE
Increase timeout for individual tlm checks

### ISSUE THREAD

**Issue by dmknutsen** [nasa/CTF#15]
We are running into an issue where for a specific telemetry check...we need to wait for an extended (and variable) amount of time.  We think it is undesirable to increase the wait for all telemetry checks because of this...can CTF provide the functionality to increase the wait/timeout time for a specific tlm check?

**Comment by twchristian** [comment]
We're adding references to the docs and examples about instruction timeout, but it already works in the released version. Here's an example. Note that "timeout" goes outside of "data", and it only applies to verification instructions that poll for conditions.
```
{​
  "instruction": "CheckEvent",
  "data": {​
    "app": "TO",
    "id": "3",
    "msg": "TO - ENABLE_OUTPUT cmd succesful for  routeMask:0x00000001"
  }​,
  "wait": 0,
  "timeout": 1
}​,
```

**Comment by dmknutsen** [comment]
Awesome - I tested this out and it is exactly what we needed.  Thanks!
