### ISSUE TITLE
Add md_platform_cfg.h to /target_defs/lx_es1_stub and /target_defs/lx_es2_stub

### ISSUE THREAD

**Issue by dmknutsen** [nasa/CTF#17]
Add the attached version of md_platform_cfg.h to /target_defs/lx_es1_stub and /target_defs/lx_es2_stub.  This will remove the MD_SIGNATURE_OPTION such that packet generated will match the packet defined in CCDD.

**Comment by dmknutsen** [comment]
[md_platform_cfg.txt](https://github.com/nasa/CTF/files/7540787/md_platform_cfg.txt)

**Comment by skliper** [comment]
Note - this is not applicable to CTF.  Handled via coordinated updates to the specific distribution, recommend closing here.

**Comment by blueoceanwater** [comment]
the user confirms it is not a CTF issue
