### ISSUE TITLE
Support verification and assign to variable of the time fields in the CCSDS header

### ISSUE THREAD

**Issue by skliper** [nasa/CTF#19]
The time fields in the CCSDS header need to be verified for certain requirements, and are also occasionally useful for controlling test flow (like doing an action x seconds after the timestamp) or relative checks via assignment to a variable.  Requesting support for both assigning the time fields to variables and including the capability to verify the time fields.

**Comment by buerge3** [comment]
The timestamp in the CCSDS headers of the tlm packets can be accessed by including the header info in the CCDD JSON tlm definitions, and then modifying the CTF config file with "CCSDS_header_info_included = true". Currently the header has to be copied into every single packet, though I am hopeful that once v1.5 comes out we will be able to define this payload structure separately and reuse it.
However, there is still one problem: The Gateway secondary header has an endianness issue. Even when the flight software is compiled in little-endian, the "seconds" value in the Gateway secondary header is always big-endian, but CTF does not know this. There should be a way to manually indicate to CTF the endianness of a parameter via the CCDD tlm definition. Adding this capability would resolve "Support verification and assign to variable of the time fields in the CCSDS header" for me.

**Comment by twchristian** [comment]
Instruction SetUserVariableFromTlmHeader will be included in v1.5
