### ISSUE TITLE
Ram drive should be cleared before starting cFS after a "power on reset" to match cFS expected behavior

### ISSUE THREAD

**Issue by skliper** [nasa/CTF#20]
CTF needs to support expected cFS behavior on all platforms.  When testing locally on Linux, since a "power on reset" doesn't clear the ram drive since it's not really doing a power cycle of the hardware, CTF needs to perform this action.  An alternative could be to use containers to execute cFS when using Linux vs running directly on the host, which would be a step closer to "flight like".

Suggestion is to clear the drive within StartCfs when running locally (on Linux) right before starting the cFS executable whenver the -RPR (process reset) flag isn't supplied:
```
# Remove ram drive if not a processor reset and it exists (expected cFS target behavior)
        if "-RPR" not in run_args:
            log.info("Removing ram drive before startup since -RPR arg was not included")
            rmtree(Path('/dev/shm/osal:RAM'), ignore_errors=True)
```

**Comment by blueoceanwater** [comment]
It is completed and will be officially released in v1.4.
