### ISSUE TITLE
CTF fails to accept variable as index in an Array

### ISSUE THREAD

**Issue by jttran5** [nasa/CTF#25]
When attempt to use the instruction "SetUserVariableFromTlm" and the tlm_variable sets to an array with a passing variable as index, CTF fails to accept this.  Please see codes below:
                {
                    "instruction": "SetUserVariable",
                    "data": {
                        "variable_name": "aggregate_payload_id",
                        "operator": "=",
                        "value": 0
                    },
                    "wait": 1
                },
               {
                    "instruction": "SetUserVariableFromTlm",
                    "data": {
                        "user_variable": "pl_time",
                        "mid": "PSM_PAYLOAD_HS_TLM_MID",
                        "tlm_variable": "payload_hs[$aggregate_payload_id$].system_time.SysTime.Seconds"
                    },
                    "wait": 1
                },

**Comment by blueoceanwater** [comment]
It is completed and will be officially released in v1.6.
